
#pragma once

#include "defines.h"

enum prime_key
{
    // from GLFW
    PRIME_KEY_A,
    PRIME_KEY_B,
    PRIME_KEY_C,
    PRIME_KEY_D,
    PRIME_KEY_E,
    PRIME_KEY_F,
    PRIME_KEY_G,
    PRIME_KEY_H,
    PRIME_KEY_I,
    PRIME_KEY_J,
    PRIME_KEY_K,
    PRIME_KEY_L,
    PRIME_KEY_M,
    PRIME_KEY_N,
    PRIME_KEY_O,
    PRIME_KEY_P,
    PRIME_KEY_Q,
    PRIME_KEY_R,
    PRIME_KEY_S,
    PRIME_KEY_T,
    PRIME_KEY_U,
    PRIME_KEY_V,
    PRIME_KEY_W,
    PRIME_KEY_X,
    PRIME_KEY_Y,
    PRIME_KEY_Z,

    PRIME_KEY_ESCAPE,
    PRIME_KEY_ENTER,
    PRIME_KEY_TAB,
    PRIME_KEY_BACK_SPACE,
    PRIME_KEY_INSERT,
    PRIME_KEY_DELETE,
    PRIME_KEY_RIGHT,
    PRIME_KEY_LEFT,
    PRIME_KEY_DOWN,
    PRIME_KEY_UP,
    PRIME_KEY_PAGE_UP,
    PRIME_KEY_PAGE_DOWN,
    PRIME_KEY_HOME,
    PRIME_KEY_END,
    PRIME_KEY_CAPS_LOCK,
    PRIME_KEY_SCROLL_LOCK,
    PRIME_KEY_NUM_LOCK,
    PRIME_KEY_PRINT_SCREEN,
    PRIME_KEY_PAUSE,
    PRIME_KEY_F1,
    PRIME_KEY_F2,
    PRIME_KEY_F3,
    PRIME_KEY_F4,
    PRIME_KEY_F5,
    PRIME_KEY_F6,
    PRIME_KEY_F7,
    PRIME_KEY_F8,
    PRIME_KEY_F9,
    PRIME_KEY_F10,
    PRIME_KEY_F11,
    PRIME_KEY_F12,

    PRIME_KEY_LEFT_SHIFT,
    PRIME_KEY_LEFT_CTRL,
    PRIME_KEY_LEFT_ALT,
    PRIME_KEY_LEFT_SUPER,
    PRIME_KEY_RIGHT_SHIFT,
    PRIME_KEY_RIGHT_CTRL,
    PRIME_KEY_RIGHT_ALT,
    PRIME_KEY_RIGHT_SUPER,
    PRIME_KEY_MENU,

    PRIME_KEY_LEFT_BRACKET, /* [ */
    PRIME_KEY_BACK_SLASH, /* \ */
    PRIME_KEY_RIGHT_BRACKET,  /* ] */
    PRIME_KEY_GRAVE_ACCENT,  /* ` */
    PRIME_KEY_SEMI_COLON, /* ; */
    PRIME_KEY_EQUAL, /* = */

    PRIME_KEY_SPACE,
    PRIME_KEY_APOSTROPHE, /* ' */
    PRIME_KEY_COMMA, /* , */
    PRIME_KEY_MINUS, /* - */
    PRIME_KEY_PERIOD, /* . */
    PRIME_KEY_SLASH, /* / */

    PRIME_KEY_0, /* 0 */
    PRIME_KEY_1, /* 1 */
    PRIME_KEY_2, /* 2 */
    PRIME_KEY_3, /* 3 */
    PRIME_KEY_4, /* 4 */
    PRIME_KEY_5, /* 5 */
    PRIME_KEY_6, /* 6 */
    PRIME_KEY_7, /* 7 */
    PRIME_KEY_8, /* 8 */
    PRIME_KEY_9, /* 9 */

    PRIME_KEY_P0,
    PRIME_KEY_P1,
    PRIME_KEY_P2,
    PRIME_KEY_P3,
    PRIME_KEY_P4,
    PRIME_KEY_P5,
    PRIME_KEY_P6,
    PRIME_KEY_P7,
    PRIME_KEY_P8,
    PRIME_KEY_P9,
    PRIME_KEY_PDECIMAL,
    PRIME_KEY_PDIVIDE,
    PRIME_KEY_PMULTIPLE,
    PRIME_KEY_PSUBTRACT,
    PRIME_KEY_PADD,
    PRIME_KEY_PENTER,
    PRIME_KEY_PEQUAL,

    PRIME_KEY_MAX
};

enum prime_button
{
    PRIME_BUTTON_LEFT,
    PRIME_BUTTON_RIGHT,
    PRIME_BUTTON_MIDDLE,

    PRIME_BUTTON_MAX
};

enum prime_action
{
    PRIME_ACTION_RELEASE,
    PRIME_ACTION_PRESS,
    PRIME_ACTION_REPEAT,

    PRIME_ACTION_MAX
};

PRIME_API const char* prime_get_key_name(u32 key);
PRIME_API const char* prime_get_button_name(u32 button);
PRIME_API const char* prime_get_action_name(u32 action);