
#pragma once

#include "buffer.h"
#include "prime/context.h"
#include "prime/defines.h"
#include "prime/font.h"
#include "input.h"
#include "layout.h"
#include "prime/logger.h"
#include "prime/mat4.h"
#include "prime/maths.h"
#include "prime/platform.h"
#include "rect.h"
#include "prime/renderer2d.h"
#include "shader.h"
#include "prime/string.h"
#include "prime/test.h"
#include "prime/texture.h"
#include "prime/window.h"
#include "prime/vec2.h"
#include "prime/vec2i.h"
#include "prime/vec3i.h"
#include "prime/vec4i.h"